project:
  type: website

lang: zh

website:
  title: "Kengroo"
  navbar:
    right:
      - icon: github
        href: https://github.com/Kengroo1024
    left:
      - text: 首页
        file: index.qmd
      - text: 考研数学
        file: 考研数学.qmd
      - text: 博客
        file: posts.qmd
      - text: 关于
        file: about.qmd
  sidebar:
    - title: 考研数学
      style: docked
      contents: 考研数学

    - title: 博文
      contents: posts
          

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    css: styles.css



