project:
  type: website

lang: zh

website:
  title: "Kengroo"
  navbar:
    right:
      - icon: github
        href: https://github.com/Kengroo1024
    left:
      - text: 首页
        file: index.qmd
      - text: 关于
        file: about.qmd
  sidebar:
    contents: posts

format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    css: styles.css



